### ISSUE TITLE
the java version of the library

### ISSUE THREAD

**Issue by FadolfHaroun** [alexstyl/RadiusTransition#1]
how can i add this to my code?
write the whole library in the README.md so we can use it.

**Comment by alexstyl** [comment]
Hi @FadolfHaroun. This sample project is not a library but rather a showcase on how to achieve a Radius Transition. 

The README file mentions that you can see how it works in the [RadiusTransition](https://github.com/alexstyl/RadiusTransition/blob/main/app/src/main/java/com/alexstyl/radiustransition/transition/RadiusTransition.kt) class.

Please have a look at that file and raise a new issue if you feel like something is missing. 
Closing this issue as it is already old.
